name: Deploy MkDocs to GitHub Pages

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  
  workflow_dispatch:

jobs:
  deploy:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Update Dependencies
        working-directory: ./docs
        run: |
          uv sync

      - name: Build MkDocs site
        working-directory: ./docs
        run: |
          mkdocs build --site-dir ../site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
