name: Deploy MkDocs to GitHub Pages

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: "3.12"
jobs:
  deploy_mkdocs:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-

      - run: pip install \
            mkdocs-material

      - run: mkdocs gh-deploy --force



      #- run: mkdocs build --site-dir site --config-file docs/mkdocs.yml


      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./docs/site

